bank_file: music/Master.bank
bank_string_file: music/Master.strings.bank
fmod_event: /move_hand
display_scale: 0.6 #pixel/mm

display_paintings: true
display_points:  true    
display_areas: true 

area:
  w: 3070 #mm
  h: 700 #mm

lidar:
  port: COM5
  # x: 1535
  # y: -100

  x: 3000
  y: -100  

paintings:
  - image_file: images/painting1.jpg
    x: 100
    y: 150
    w: 390
    h: 390 
  - image_file: images/painting2.jpg
    x: 590
    y: 0
    w: 440
    h: 700
  - image_file: images/painting3.jpg
    x: 1130
    y: 190
    w: 770
    h: 300 
  - image_file: images/painting4.jpg
    x: 2000
    y: 150
    w: 390
    h: 390
  - image_file: images/painting5.jpg
    x: 2490
    y: 150
    w: 480
    h: 390          

bank_params:
  - id: detail
    values:
      # area
      - value: 2  #P1_D2
        rect: {x: 0, y: 0, w: 3070, h: 700}

      # painting 1
      - value: 1 #P1_D1
        rect: {x: 100, y: 150, w: 390, h: 390}

      # painting 2
      - value: 3 #P2_D1
        rect: {x: 590, y: 0, w: 440, h: 700}
      - value: 4 #P2_D2        
        rect: {x: 620, y: 100, w: 130, h: 500}
      - value: 6 #P2_D4
        rect: {x: 750, y: 100, w: 130, h: 500}
      - value: 5 #P2_D3        
        rect: {x: 880, y: 100, w: 130, h: 500}            

      # painitng 3
      - value: 9 #P3_D3
        rect: {x: 1130, y: 190, w: 770, h: 300}
      - value: 8 #P3_D2
        rect: {x: 1130, y: 200, w: 200, h: 280}
      - value: 8 #P3_D2
        rect: {x: 1700, y: 200, w: 200, h: 280}        
      
      # painting 4
      - value: 10 #P4_D1
        rect: {x: 2000, y: 150, w: 390, h: 390}
      - value: 11 #P4_D1
        rect: {x: 2145, y: 295, w: 100, h: 100}

      # painting 5
      - value: 13 #P5_D1
        rect: {x: 2490, y: 150, w: 480, h: 390}             
      - value: 15 #P5_D1
        rect: {x: 2640, y: 245, w: 200, h: 200}             