enable_display: true
enable_lidar: true
enable_sound: true
enable_api: false

picture_conf: pictures/2024_2/painting1.yaml

lidar:
  serial: COM4

api:
  port: 8080

display:  
  show_paintings: false
  show_points:  true    
  show_areas: true 
  scale: 1 #pixel/mm
