enable_display: false
enable_lidar: true
enable_sound: true
enable_api: false

picture_conf: pictures/2024_2/painting2.yaml

lidar:
  serial: /dev/ttyS0

api:
  port: 8080

display:  
  show_paintings: false
  show_points:  true    
  show_areas: true 
  scale: 1 #pixel/mm
