enable_display: false
enable_lidar: true
enable_sound: true
enable_api: true

picture_path: pictures/2024

lidar_config:
  serial: COM5

api_config:
  port: 8080

display_config:  
  display_paintings: true
  display_points:  true    
  display_areas: true 
  display_scale: 0.6 #pixel/mm