enable_display: true
enable_lidar: true
enable_sound: true
enable_api: true

picture_conf: pictures/2024/painting1.yaml

lidar:
  serial: COM5

api:
  port: 8080

display:  
  show_paintings: true
  show_points:  true    
  show_areas: true 
  scale: 1 #pixel/mm